fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    group:
        group_class: App\Entity\Group
    service:
            mailer: fos_user.mailer.twig_swift
    from_email:
        address: '%sender_email%'
        sender_name: '%sender_name%'
