fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    service:
            mailer: fos_user.mailer.twig_swift
    from_email:
        address: '%env(resolve:EMAIL_SENDER_ADDRESS)%'
        sender_name: '%env(resolve:EMAIL_SENDER_NAME)%'
