fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Sonata\UserBundle\Entity\BaseUser
    #user_class: App\Entity\User
    group:
        #group_class: App\Entity\Group
        group_class:   Sonata\UserBundle\Entity\BaseGroup
        group_manager: sonata.user.orm.group_manager

    service:
            mailer: fos_user.mailer.twig_swift
            user_manager: sonata.user.orm.user_manager
    from_email:
        address: '%sender_email%'
        sender_name: '%sender_name%'
