security:
    # encoders:
    #     FOS\UserBundle\Model\UserInterface: bcrypt
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    role_hierarchy:
        ROLE_USER: ROLE_USER  # The normal user
        ROLE_SUPER_ADMIN: ROLE_ADMIN # The system admin
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider: fos_userbundle
            anonymous: ~
            pattern: ^/
            logout_on_user_change: true
            form_login:
                login_path: user_login
                check_path: user_login
                default_target_path:  /cmm/dashboard
            logout:
                path: user_logout
                target: /
        login:
            pattern: ^/user/login$
            anonymous: ~
            logout_on_user_change: true

    access_control:
        - { path: ^/user/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cmm/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cmm/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cmm/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cmm/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cmm/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/.*, role: [ROLE_ADMIN, ROLE_SONATA_ADMI] }

acl:
    connection: default
