sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    assets:
        extra_stylesheets:
            - bundles/sonataadmin/vendor/admin-lte/dist/css/skins/skin-green.css

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
